name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller loguru
        
    - name: Build executable
      run: |
        .\build.bat
        
    - name: Get tag name
      id: tag
      run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      shell: bash
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ steps.tag.outputs.TAG_NAME }}
        body: |
          ## What's New
          
          See the commits since the last release for detailed changes.
          
          ## Download
          Download `MSFS-SimRate-Monitor.exe` below and run it alongside MSFS.
          
          ## Features
          - Shows current sim rate in a draggable overlay
          - Lightweight (~20MB memory usage)
          - No mods or plugins required
        files: ./dist/MSFS-SimRate-Monitor.exe
        draft: false
        prerelease: false